/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "2.2.0"
    application
}

dependencies {
    implementation(project(":core"))
    implementation(project(":utilities"))
    implementation(project(":ui"))

    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.jupiter.launcher)
}

application {
    mainClass.set("org.example.AppKt")
}

tasks.test {
    useJUnitPlatform()
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}
